language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: shareourideas-nodejs
  api_key:
    secure: c3fdpQE49YeM47QQNhpZKXzTjwRRV9rIhum/ELETY5TkMlRZRJbr6hGagqMVajtg2sbv27q8s4UZFL7INzfOlsMmelX9J9ZNU2xM1ruwAPMObPMapylQrS/tRkWGL9K1hNdShtjkHnKkrFyXIZW5khuikmNrEk7CLjHvTgpyl61pbhM9YVPy/esc8iOr7j/7nOTZM+46NSl7xPvcs5iUtVvpVB0uomZUwenfI3iDEmf9U9GcDvWJBmcwim+8SatmIiUOYoqLRNgTOmt6LBuW/J8duRR0igFqlgu48ITBs+oASAfj7ZSeE0CAWdaPSZPvMY9RThmI4udXqbySLIMnlsI5oja5KOD1qE6xy9FWkcJ3bcvZ/ryMh3Gqule9YHnj34afGGPBcrGA1tMmZRQL7ktRcekFBzAEm3BJJHZnZojGwxJmDgNwhElicgc2f6+4CdT4mKrTIE5exqWUF2cEHjb3MPIn5xXytToJxLbSFgrc7nJ1fk8pwJRaoFYSI7Sy8jMM58HLFTjTWDd27qODoeUuroppSLrhiZ73qvezQNrrA32FQgTVbVw7TV1KS/nvhwkzv8EEZFqgVHjdZQjWEXgEE70dUf7J8dLg7CGgvvvgqn3g0Wu4VOEm/Atuvtds5WoRiWkMkWTlfV2csVvu9LgmtxzMy+jcu+7dl5C4lw8=
